package net.darmo_creations.mccode.interpreter;

/**
 * A stack trace element generated by {@link Scope} objects.
 */
public record StackTraceElement(String scopeName) {
  /**
   * Create a stack trace element.
   *
   * @param scopeName Name of the scope this element represents.
   */
  public StackTraceElement {
  }
}
