package net.darmo_creations.mccode.interpreter;

/**
 * A stack trace element generated by {@link Scope} objects.
 *
 * @param scopeName Name of the scope this element represents.
 */
public record StackTraceElement(String scopeName) {
}
