package net.darmo_creations.mccode.interpreter;

/**
 * A stack trace element generated by {@link Scope} objects.
 *
 * @param scopeName Name of the scope this element represents.
 * @param line      Line of the parent scope’s program this element has been created at.
 * @param column    Column of the parent scope’s program this element has been created at.
 */
public record StackTraceElement(String scopeName, int line, int column) {
}
